// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Game.Data
{
    using System;
    using System.Collections.Generic;
    using Game.Data;
    using SQLite4Unity3d;
    
    
    public struct Skillblock
    {
        
        // 技能
      [PrimaryKey] 
        public double Id {get;set;}
        // Block播放顺序
       public double BlockIndex {get;set;}
        // 触发条件
       public List<string> Condition {get;set;}
        // Buff作用目标类型
       public double TargetType {get;set;}
        // 作用目标数量
       public double TargetNum {get;set;}
        // 添加的Buff
       public List<double> Buffs {get;set;}
        // 系数
       public List<double> Ratio {get;set;}
        // 公式
       public List<string> BuffValueFormula {get;set;}
    }
}
