// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Game.Data
{
    using System;
    using System.Collections.Generic;
    using Game.Data;
    using SQLite4Unity3d;
    
    
    public struct Skill
    {
        
        // 技能
      [PrimaryKey] 
       public double Id {get;set;}
        // 包含的技能
       public List<double> SkillBlocks {get;set;}
        // 下个等级id
       public double NextLevelID {get;set;}
        // 图标
       public double Icon {get;set;}
        // 消耗
       public double Consume {get;set;}
        // 特效类型
       public double EffectType {get;set;}
        // 特效路径
       public string Effect {get;set;}
    }
}
